/** Display-unit selection and conversion. The catalogue is generated by sdr_cli.units; SI stays the wire truth. */
import { writable } from 'svelte/store';
import catalogue from './units.catalogue.json';

export type UnitPrefs = { system: 'metric' | 'imperial'; overrides: Record<string, string> };
interface UnitDef { id: string; label: string; factor: number; offset: number }
interface QuantityDef { si: string | null; units: UnitDef[] }

const quantities = catalogue.quantities as Record<string, QuantityDef>;
const systems = catalogue.systems as Record<string, Record<string, string>>;
const KEY = 'sdr.units';

export function loadUnitPrefs(): UnitPrefs {
  try {
    const raw = JSON.parse(localStorage.getItem(KEY) ?? 'null');
    if (raw && (raw.system === 'metric' || raw.system === 'imperial')) {
      const overrides: Record<string, string> = {};
      if (raw.overrides && typeof raw.overrides === 'object') {
        for (const [q, u] of Object.entries(raw.overrides)) if (typeof u === 'string') overrides[q] = u;
      }
      return { system: raw.system, overrides };
    }
  } catch {
    /* no storage or bad JSON */
  }
  return { system: 'metric', overrides: {} };
}

export function saveUnitPrefs(p: UnitPrefs): void {
  try {
    localStorage.setItem(KEY, JSON.stringify(p));
  } catch {
    /* per-viewer convenience only */
  }
}

export const unitPrefs = writable<UnitPrefs>(loadUnitPrefs());

function unitDef(quantity: string, unit: string): UnitDef | undefined {
  return quantities[quantity]?.units.find(u => u.id === unit);
}

/** Card override, then viewer override, then the system default. Null for dimensionless quantities. */
export function unitFor(quantity: string, cardUnits: Record<string, string> | undefined, prefs: UnitPrefs): string | null {
  const q = quantities[quantity];
  if (!q || q.units.length === 0) return null;
  for (const id of [cardUnits?.[quantity], prefs.overrides[quantity], systems[prefs.system]?.[quantity]]) {
    if (id && unitDef(quantity, id)) return id;
  }
  return q.si;
}

export function convert(si: number, quantity: string, unit: string): number {
  const u = unitDef(quantity, unit);
  return u ? si * u.factor + u.offset : si;
}

export function toSI(display: number, quantity: string, unit: string): number {
  const u = unitDef(quantity, unit);
  return u ? (display - u.offset) / u.factor : display;
}

export function format(si: number, quantity: string, unit: string | null, digits: number): string {
  if (!Number.isFinite(si)) return '—';
  const v = unit ? convert(si, quantity, unit) : si;
  return v.toFixed(digits);
}

export function unitLabel(quantity: string, unit: string | null): string {
  if (!unit) return '';
  return unitDef(quantity, unit)?.label ?? unit;
}
